name = "TASOPT"
uuid = "22dd2482-b234-48ce-b849-20a4e029c823"
authors = ["Prashanth Prakash <prash@mit.edu> and contributors"]
version = "3.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]

[compat]
julia = "1.10 - 1"
BenchmarkTools = "1.6"
CSV = "0.10.15 - 0.10"
DifferentialEquations = "7.16.1 - 7.16"
DocStringExtensions = "0.9.4 - 0.9"
ForwardDiff = "0.10.38 - 0.10"
JLD2 = "0.5.12 - 0.5"
NLopt = "1.1.3 - 1.1"
NLsolve = "4.5.1 - 4.5"
Plots = "1.40 - 1"
Roots = "2.2.7 - 2.2"
StaticArrays = "1.9.13 - 1.9"
StatsPlots = "0.15.7 - 0.15"
Tables = "1.12.0 - 1.12"
Zygote = "0.7.6"